name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  SNAPSHOT_ARTIFACTS: ${{ github.workspace }}/snapshots
  TEST_RUNNER_SNAPSHOT_ARTIFACTS: ${{ github.workspace }}/snapshots

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 16.2
      run: ls -l /Applications && sudo xcode-select -s /Applications/Xcode_16.2.app
    - name: Build, test, and code coverage
      run: env && make
    - name: Archive test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: snapshots
        path: ${{ env.SNAPSHOT_ARTIFACTS }}
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: 54c92d8df32d9a1b64d945f2e76696f1
        filename: SwiftGRDBTCA-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
